commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -158,8 +158,8 @@ jobs:
       name: Check tag version
       if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/V')
       runs-on: ubuntu-24.04
-      # permissions:
-      #   contents: write
+      permissions:
+        contents: write
       needs: common
       concurrency:
         group: release-${{ github.ref }}
@@ -176,6 +176,13 @@ jobs:
             RAW_TAG="${GITHUB_REF#refs/tags/}"      # 例如 v1.0.1 或 V1.0.1
             TAG_VERSION="${RAW_TAG#[vV]}"           # 去掉前导 v 或 V -> 1.0.1
 
+            # 读取并清理文件里的 version= 值
+            if [ ! -f library.properties ]; then
+              echo "❌ library.properties not found"
+              exit 1
+            fi
+            FILE_VERSION="$(awk -F= '/^[[:space:]]*version[[:space:]]*=/ {print $2; exit}' library.properties \
+              | tr -d '\r' | xargs)"
             echo "📦 Tag version: $TAG_VERSION"
             echo "🧾 File version: $FILE_VERSION"
 
